name: Dynamic README injection
on:
  schedule:
    - cron: '0 3 * * *'  # Executa a cada dia 00:00
  push:                  # Reconhece mudanças no repositório
    branches:
      - main
  workflow_dispatch:     # Permite disparar manualmente o workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Execute script
        run: node .

      - name: Commit and push changes
        run: |
          git config user.name "digonomundo"
          git config user.email "rodrigo.dias@digonomundo.com"
          git add .
          git commit -m "[Automação] README atualizado com a nova frase do quote!"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
