name: Dynamic README injection
on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos para testes
  workflow_dispatch:
jobs:
  get-office-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Let the magic happen
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: yarn

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "digonomundo"
          git config --global user.email "rodrigo.dias@digonomundo.com"
          git commit -m "[Automação] README atualizado com a nova frase do quote!"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
