name: Dynamic README injection
on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos para testes
  workflow_dispatch:
jobs:
  get-office-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Let the magic happen
        uses: actions/setup-node@v3  # Usando a versão mais recente
        with:
          node-version: 14.6.0

      - run: yarn

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "[Automação] README atualizado com a nova frase do quote!"
          else
            echo "Nada para commitar!"
          fi

      - name: Push
        uses: ad-m/github-push-action@v0.6.0  # Versão estável
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
